import { PageHeader } from 'layout/PageHeader';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Myxellia Frontend Developer Test</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <PageHeader />
      </main>
    </>
  );
}
