import {
  Box,
  Button,
  Container,
  Divider,
  Flex,
  Heading,
  Text
} from '@chakra-ui/react';
import { CustomersOverviewSection } from 'components/CustomersOverviewSection';
import { ListingOverviewSection } from 'components/ListingOverviewSection';
import { PropertyOverviewSection } from 'components/PropertyOverviewSection';
import { SalesOverviewSection } from 'components/SalesOverviewSection';
import { TopSellingSection } from 'components/TopSellingSection';
import { TotalBalanceSection } from 'components/TotalBalanceSection';
import { VirtualAssistantPopup } from 'components/Widgets';
import { PageHeader } from 'layout/PageHeader';
import { TabLink } from 'layout/header/TabLink';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Myxellia Frontend Developer Test</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <PageHeader />
        <Container className={styles.content_body} maxWidth='100%'>
          <Flex align='center' gap='.4rem' mb='1.2rem'>
            <Image
              src='/wave_greeting.png'
              alt='Waving Hand'
              height={29}
              width={29}
            />
            <Heading fontSize='2rem'>Hi Ahmed</Heading>
          </Flex>
          <Text fontSize='1.2rem' fontWeight='400' color={'#3d3d3d'}>
            Welcome to your Dashboard
          </Text>
          <Flex direction='column' gap='2rem' mt='2rem'>
            <Flex gap='2rem' minH='32.5rem' className={styles.inline_layout}>
              <Flex
                className={`${styles.overview} ${styles.sales_overview}`}
                flex={856}
                direction={'column'}
              >
                <SalesOverviewSection />
              </Flex>
              <Flex gap='1.7rem' direction='column' flex={407}>
                <Box
                  className={`${styles.overview} ${styles.property_overview}`}
                  flex={1}
                >
                  <PropertyOverviewSection />
                </Box>
                <Box
                  className={`${styles.overview} ${styles.customer_overvview}`}
                  flex={1}
                >
                  <CustomersOverviewSection />
                </Box>
              </Flex>
            </Flex>
            <Flex gap='2rem' minH='32.5rem' className={styles.inline_layout}>
              <Flex
                direction={'column'}
                className={`${styles.overview} ${styles.listings_overview}`}
                flex={475}
              >
                <ListingOverviewSection />
              </Flex>
              <Box
                className={`${styles.overview} ${styles.total_balance}`}
                flex={418}
              >
                <TotalBalanceSection />
              </Box>
              <Box
                className={`${styles.overview} ${styles.top_selling}`}
                flex={350}
              >
                <TopSellingSection />
              </Box>
            </Flex>
          </Flex>
        </Container>
        <VirtualAssistantPopup />
      </main>
    </>
  );
}
